services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "5055:5055"
    volumes:
      - ${FAST_ROOT}/appdata/overseerr:/config
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
