services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "8989:8989"
    volumes:
      - ${FAST_ROOT}/appdata/sonarr:/config
      - ${BULK_ROOT}/media/tv:/tv
      - ${BULK_ROOT}/downloads:/downloads
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
