services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${FAST_ROOT}/appdata/dockge:/app/data
      - ${FAST_ROOT}/homelab/compose:/opt/stacks
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
